### ISSUE TITLE
Duplicate symbols after VS Code update

### ISSUE THREAD

**Issue by awulkan** [pokey/cursorless-vscode#111]
After installing Cursorless I got an update for VS Code, so I chose to install it. This restarted the editor.
After it launched again I got duplicate Cursorless symbols in the code.
![image of duplicate symbols](https://i.imgur.com/nPg1r8X.png)
(The code is blurred since it's from a closed source application that I don't own)

Restarting the editor again manually appears to have solved it though.

**Comment by pokey** [comment]
Ooh interesting thanks for filing!

**Comment by AndreasArvidsson** [comment]
A recently ran into the same issue.
I think this could have to do with `NavigationMap`
