### ISSUE TITLE
Change "copy", "paste" and "cut" actions by moving selection and using built-ins

### ISSUE THREAD

**Issue by pokey** [pokey/cursorless-vscode#127]
There are a lot of smarts baked into the built-in copy, paste, and cut actions.  Rather than reimplementing them ourselves, it's probably easiest to first `setSelection`, then issue the built-in command, then `setSelection` back

**Comment by AndreasArvidsson** [comment]
Vscode implementation
https://github.com/microsoft/vscode/blob/b66a9f6308e427aa8c80197f3b27277a11443338/src/vs/editor/common/controller/cursorTypeOperations.ts#L108

**Comment by pokey** [comment]
Yep that's certainly part of it. There also must be code somewhere along the chain to be smart about tracking multi-cursor multi-line copies, and I think I remember seeing code trying to be smart about indentation, but not positive bout that one

**Comment by AndreasArvidsson** [comment]
I as wanted to store that reference. I think I figure out how the smart logic works internally and agree we should use the the internal copy and past function.
