### ISSUE TITLE
Support "enclosing <symbol>" transformation

### ISSUE THREAD

**Issue by pokey** [pokey/cursorless-vscode#14]
We'd like to support transformations such as "outer round" to take everything inside and including the parentheses containing a token, as well as "inner round", "inner square", etc.

Would also be nice to support selecting the delimiter symbols themselves, eg the open and close paren.  This could be eg "border round", "border square", etc.  Or "disc", or "doughnut", or "bound" or something.  This version of the transformation would be useful when combined with a list-based "replace with" command, so could say eg "replace border round with square" to change enclosing parens to square brackets.

**Comment by pokey** [comment]
Any thoughts on term for selecting the delimiter symbols themselves?  Considering:

- "boundary"
- "bound"
- "border"
- "doughnut"
- "disc"
- "edge"
- "flank"
- "hedge"
- "fringe"

cc/ @brxck @andreasarvidsson

**Comment by brxck** [comment]
"bound" would be my vote.

**Comment by pokey** [comment]
Yeah I like "bound" too.  Will need to see if it conflicts with "round" in practice

**Comment by AndreasArvidsson** [comment]
Bound sounds good
