### ISSUE TITLE
Support "replace with" action

### ISSUE THREAD

**Issue by pokey** [pokey/cursorless-vscode#15]
Eg "replace fine with camel hello world".  It would support arbitrary format string ie "replace `<target>` with `<format_string>`".  The actual `replaceWith` function would accept a list of strings so that it can operate on compound targets.  So talon-side we could support "replace fine and bar with camel hello world and snake hello there".

Could also support things other than format strings after the "with", eg "spell `<letters>`" or "word" or "round" / "curly" / "square" that would return eg `["(", ")"]`, to combine with ["boundary"](https://github.com/pokey/cursorless-vscode/issues/14), allowing commands like "replace border round with square"

It is tempting to support cursorless targets after the "with" as well, eg "replace fine with gust", but this functionality is subsumed by "bring", eg "bring gust to fine", so not sure it's worth the added complexity

**Comment by pokey** [comment]
What are people's thoughts on just reusing "bring" for this, eg "bring camel hello world to fine"? cc/ @brxck @AndreasArvidsson @knausj85

**Comment by brxck** [comment]
I think this makes sense that this could be under the same command, though it feels like we might be stretching the word "bring."

**Comment by AndreasArvidsson** [comment]
Yeah not sure if bring is the correct therm.

What if you want to insert a word used in the alphabet? "bring air to bat" vs "insert air at bat" or "replace bat with air"

**Comment by pokey** [comment]
To use a word in the alphabet you'd say "bring word air to bat". Yeah I don't feel strongly in this one just trying to reduce the size of the vocabulary to learn haha
