### ISSUE TITLE
Fix nondeterministic test failures

### ISSUE THREAD

**Issue by pokey** [pokey/cursorless-vscode#173]
Let's start by just retrying tests 3 times if they fail.  This approach is terrible, because it swallows all nondeterministic bugs, but at least we can start requiring CI passes, unlike now where they're disabled because they fail

_Originally posted by @pokey in https://github.com/pokey/cursorless-vscode/pull/172#r680547202_

**Comment by pokey** [comment]
@AndreasArvidsson @brxck lets move the sleep discussion here. Here's @AndreasArvidsson's comment from the PR:

> @brxck Is it only mac that needs the sleep time? If that's the case we could probably do something like this. Not as optimal as removing the sleep totally foriall platforms but still better than having them where they are not needed.
> 
> ```
> 
> if (os.platform() === "darwin") {
> 
>         await new Promise((resolve) => setTimeout(resolve, 100));
> 
>  }
> 
> ```

**Comment by pokey** [comment]
@AndreasArvidsson It's actually only macOS in CI, so we might be able to be even more specific but yeah could do that for now

It's quite odd it needs a sleep at all tbh because there's nothing async going on there. It's just setting some stuff in an object.

**Comment by AndreasArvidsson** [comment]
Then that sounds like a good solution :)

**Comment by pokey** [comment]
`CI`. See https://docs.github.com/en/actions/reference/environment-variables

**Comment by brxck** [comment]
I'll say that tests on Ubuntu occasionally had the same problem, including my own (not slow) machine.

It is a weird problem... I had an alternative idea of adding retry logic to where we check the navigationMap?

**Comment by AndreasArvidsson** [comment]
@pokey I should probably work
```
if (process.platform === "darwin" && process.env["CI"]) {
        await new Promise((resolve) => setTimeout(resolve, 100));
}
```

**Comment by pokey** [comment]
Yeah given @brxck 's comment I think exponential backoff is the way to go

**Comment by AndreasArvidsson** [comment]
On windows it seems to work fine without sleep. So setings per operating system might be a good idea anyways.

**Comment by AndreasArvidsson** [comment]
A retry logic is now implemented. Doing three tries with 100 mill seconds between each.

**Comment by pokey** [comment]
Looks like that still failed; I switched it to exponential so hopefully that's more reliable

https://github.com/pokey/cursorless-vscode/pull/174

**Comment by pokey** [comment]
Weird that didn't seem to help. Maybe it's not a timing thing? Maybe it's actually just nondeterministic for some reason? We should figure out how get more useful output from the assertion

**Comment by AndreasArvidsson** [comment]
Yes if a three second sleep doesn't help it's not that.

**Comment by pokey** [comment]
Yeah the first question to figure out is whether it is not doing the decorations or if it is doing them but they don't match our expectations

**Comment by pokey** [comment]
I kind of have the feeling that the sleep makes no difference 😂

**Comment by AndreasArvidsson** [comment]
Well that's just great then :D
