### ISSUE TITLE
Merge sequential pending change highlights

### ISSUE THREAD

**Issue by pokey** [pokey/cursorless-vscode#2]
There are a couple commands where the pending change highlights appear in sequence. This slows down the action and makes it so that sometimes the cursorless decorations will move before another command can be executed. We'd like to make these commands show the highlights at the same time. The commands are:

- use
- carve

**Comment by AndreasArvidsson** [comment]
Could you expand on how you want the use/bring decorations to function?

**Comment by pokey** [comment]
I think this one was basically solved by reducing highlight time. The issue was if you say "carve air take bat" in one command, the "bat" highlight would have changed because redecoration debounce was too short relative to highlight timeout. I don't think that's an issue anymore but prob worth retesting just to be sure.

**Comment by AndreasArvidsson** [comment]
Okay but for cut is already fixed anyways :)
https://github.com/pokey/cursorless-vscode/pull/141
