### ISSUE TITLE
"Clear after" doesn't work as expected

### ISSUE THREAD

**Issue by pokey** [pokey/cursorless-vscode#208]
I would expect it to delete the trailing delimiter and leave the cursor there

**Comment by AndreasArvidsson** [comment]
Well after inner selection is just "end of". So far only outer selection has anything to do with delimiters.

**Comment by pokey** [comment]
Then how would you propose to do what I wanted to have happen? It is useful functionality

**Comment by AndreasArvidsson** [comment]
This is a hard one. We could always add a proper position for end of but we still have a problem with `change after air to hello` that command shouldn't actually replace anything and just insert the text after.
We could of course make the actions themselves aware of different position and have different actions do different things with the after position, but that's a tricky one as well.

**Comment by pokey** [comment]
So I think based on our last discussion, we want to support this one, no?  Because "after" would transform the selection into something where the content itself is the delimiter, so "clear" would target it

**Comment by AndreasArvidsson** [comment]
Yes this will be supported after we do the new oo targets.

**Comment by pokey** [comment]
Better to solve this one with #309
