### ISSUE TITLE
"value" broken for patterns in typescript

### ISSUE THREAD

**Issue by pokey** [pokey/cursorless-vscode#2082]
```ts
const { aaa: bbb } = ccc;
```

`"value air"` should be `bbb`.

**Comment by AndreasArvidsson** [comment]
Are you really sure about that? It's not really a value it's an rename/as. `bbb` is more like the name

**Comment by pokey** [comment]
I agree with you intellectually, but I would let the lizard brain win this one 😄

**Comment by AndreasArvidsson** [comment]
I kind of feel the same way about the types in a typescript interface. They are not really values, but I end up calling them values anyhow.
