### ISSUE TITLE
"Value" scope type in Python doesn't work when value contains array index

### ISSUE THREAD

**Issue by pokey** [pokey/cursorless-vscode#223]
For example:

```python
{
    "foo": bar[0],
}
```

Saying "take value zero" results in the error `Cannot read property 'startPosition' of null`

**Comment by AndreasArvidsson** [comment]
@pokey This works find for me using latest code in master

**Comment by pokey** [comment]
@AndreasArvidsson did you try this on TS or python?  I observed the failure in Python

**Comment by AndreasArvidsson** [comment]
@pokey ah ts. Gonna try py
