### ISSUE TITLE
Add modifier preferences support

### ISSUE THREAD

**Issue by pokey** [pokey/cursorless-vscode#230]
these preferences would be handled like insideOutsidePreferences

**Comment by AndreasArvidsson** [comment]
Is this issue just about adding support for the preferences or actually implementing for the above named actions?

**Comment by pokey** [comment]
If you have a PR that adds support, and uses it in at least one place, I'd rename this issue and file a new one to track using it in the other actions

**Comment by AndreasArvidsson** [comment]
@pokey Yes the clean up pr have support for this
I'm a bit unsure how useful it will be though for drink or pour
`post air void` => `pour token air`
`post air spam` => `pour arg air`

I guess where its most useful is for functions. `pour funk`

**Comment by pokey** [comment]
I think "drink" is maybe a bit more useful than "pour". But mostly "pour" just comes along for the ride because it's just easier and more consistent to support it if we're already doing it for "drink" and "clone"
