### ISSUE TITLE
Support "type" transformation

### ISSUE THREAD

**Issue by brxck** [pokey/cursorless-vscode#24]
Would it be possible to add a "type" transformation? In TypeScript, for example:

```typescript
const logs: { user: string; event: string }[] = [];
```

I think being able to "take type" and select `{ user: string; event: string }[]` it would be very useful.

Less important imo, but there are also the cases of generics and type parameters to consider?

**Comment by pokey** [comment]
Yep that's definitely doable

Can you elaborate on your comment re generics and type parameters?

**Comment by pokey** [comment]
In case anyone wants to pick this one up, it should be quite similar to the way "value" is implemented:
- [python side](https://github.com/pokey/cursorless-talon/blob/854d238bf520a68cdd277a681f4bb002a1297e9d/src/primitive_target.py#L105)
- [extension type def](https://github.com/pokey/cursorless-vscode/blob/974c91ba2d5341c35b29918a78f9dfc1164788ae/src/Types.ts#L61)
- [implementation](https://github.com/pokey/cursorless-vscode/blob/974c91ba2d5341c35b29918a78f9dfc1164788ae/src/languages/getPojoMatchers.ts#L30-L50)

**Comment by brxck** [comment]
So I vaguely referred to those other things because I'm relatively new to TypeScript so I don't have strong opinions on how I'd like them to work.

Here's an example lifted from the TypeScript docs: 

```typescript
function identity<Type>(arg: Type): Type {
    return arg;
}
```

There's two different types related to the function:

- the type variable `<Type>` — should it have its own transformation?
- the return type `Type` — which I'd probably expect to be referenced by the "type" transformation

The type variable can appear again at call time, here it's `<string>`:

```typescript
let output = identity<string>("myString");
```

**Comment by brxck** [comment]
I'm unsure how the AST looks here & other details under the hood, but I would think that the "type" transformation should also cover type aliases and interface declarations.

```typescript
type Point {
  x: number;
  y: number;
}
```

It would also be useful to reference properties of an object type similar to the way that the "map" transformation works on objects.
