### ISSUE TITLE
Hats don't show up when the line contains a `£`

### ISSUE THREAD

**Issue by pokey** [pokey/cursorless-vscode#315]
In the following line:

```
Hello testing whatever £
```

No hats appear over the given line:

![image](https://user-images.githubusercontent.com/755842/140643281-6a4007bd-ab00-4800-83b5-a5849cb50f79.png)

**Comment by AndreasArvidsson** [comment]
@pokey It's the same with Swedish characters which is a bummer.

**Comment by pokey** [comment]
Ah strange yeah maybe it broke with that selection update PR? I'll take a look

**Comment by AndreasArvidsson** [comment]
Please do because right now I can't use the draft editor which is a real pain.

**Comment by pokey** [comment]
See https://github.com/microsoft/vscode/issues/136676

**Comment by AndreasArvidsson** [comment]
@pokey This seems to be solved in 1.62.3. Can you verify?
