### ISSUE TITLE
Add new index-based pattern matchers

### ISSUE THREAD

**Issue by pokey** [pokey/cursorless-vscode#393]
- [x] `foo[0]`: Select the first named child of a node with type `foo`
- [ ] `foo[bar][0]`: Select the first child at field `bar` of a node with type `foo`

**Comment by pokey** [comment]
As discussed in https://github.com/pokey/cursorless-vscode/pull/395#issuecomment-1005165205, let's file a separate issue for selecting the nth child at a particular field.  The syntax listed in item 2 of the description here should be referring to the first child `foo[bar]` (ie a grandchild if `foo`).

**Comment by pokey** [comment]
@AndreasArvidsson any suggestions for syntax for selecting nth child at a particular field name?  `foo[bar.0]`? `foo[bar[0]]`?

**Comment by AndreasArvidsson** [comment]
foo[bar.0] was my first thought.

**Comment by AndreasArvidsson** [comment]
Last task is not done yet

**Comment by pokey** [comment]
> Last task is not done yet

that one is tracked in #427 so we can close this one 👍
