### ISSUE TITLE
Fix "past end of line"

### ISSUE THREAD

**Issue by pokey** [pokey/cursorless-vscode#4]
When issuing a command such as "chuck gust past end of line", cursorless incorrectly assumes that "end of line" refers to the current cursor line rather than the line containing "gust".

**Comment by pokey** [comment]
Fwiw I think this one will fall out of the inference rewrite for #69

**Comment by pokey** [comment]
Pretty sure this one is still a problem

**Comment by AndreasArvidsson** [comment]
What exactly isn't working? What I can tell it works as expected and we do have a test for it.
https://github.com/pokey/cursorless-vscode/blob/main/src/test/suite/fixtures/recorded/inference/takeAirPastEndOfLine.yml

**Comment by pokey** [comment]
I believe "chuck air past end of line" deletes the trailing newline, which, while I understand why it happens, is not desired. It should behave the same as "tail"

**Comment by AndreasArvidsson** [comment]
I agree that its not the desired behavior but also not really the same problem described in this issue.

**Comment by pokey** [comment]
Ah right sorry should have read it closer 😅

**Comment by pokey** [comment]
For posterity's sake, the proper issue is #209
