### ISSUE TITLE
Add support for url scope type

### ISSUE THREAD

**Issue by AndreasArvidsson** [pokey/cursorless-vscode#426]
eg
`https://code.visualstudio.com/api/extension-guides/notebook`

**Comment by pokey** [comment]
I'm pretty sure I know what you mean but a quick example would be nice

**Comment by alexhwoods** [comment]
Is it cool if I take this one guys?

**Comment by AndreasArvidsson** [comment]
go ahead

**Comment by pokey** [comment]
Fixed by #529
