### ISSUE TITLE
Update debug setting with an disabled option

### ISSUE THREAD

**Issue by AndreasArvidsson** [pokey/cursorless-vscode#448]
In this case debug log is disabled even in extension development mode

**Comment by pokey** [comment]
By "debug mode" do you mean when the extension is run in development mode? What's your use case?

**Comment by AndreasArvidsson** [comment]
Ahh development mode was what I was thinking about

**Comment by AndreasArvidsson** [comment]
Turns out I wasn't keeping track of my own settings. Just disabling debug in cursorless will disable it for other extensions
