### ISSUE TITLE
Figure out how to run a code action without first setting the selection

### ISSUE THREAD

**Issue by pokey** [pokey/cursorless-vscode#53]
The command extract that currently [first sets the selection](https://github.com/pokey/cursorless-vscode/blob/33c7f9dd6dcc76bf5a979af32daae18b936fa1a9/src/actions/extractVariable.ts#L21) because VSCode action execution not on cursor is finicky.  We'd like to figure out how to get this to work

**Comment by AndreasArvidsson** [comment]
We now have a solution for this which is used for comment and indents. But extract is a little bit special since you have to wait for the name popup.

**Comment by pokey** [comment]
Not sure this is worth the effort
