### ISSUE TITLE
Make test case recorder

### ISSUE THREAD

**Issue by pokey** [pokey/cursorless-vscode#59]
**Goal**: to make it super lightweight to make a new test case so that you don’t think twice about it, while keeping them robust enough not to rot if we rework internals

- New command `cursorless.recordTestCase`, which asks for a test case name / maybe directory
- Waits for next cursorless command
- On next cursorless command, takes a snapshot of current file, including cursor locations, visible lines, file type, and relevant decorations
- Takes snapshot after cursorless command, including cursor and visible lines
- Saves before, command, context, and after as a test case
- Then add code that can parse this type of fixture and run it as a test
- I'd argue that cursorless command should be captured pre-inference, but don't feel strongly
- This technique can be used for testing transformations, inside / outside, actions, etc
- For example, to check whether the delimiter / inside outside stuff is working for eg "type" transformation, can run the command with "take" and "Chuck". This makes it robust to changes in internal representations, at the expense of being slightly less granular
- Also save highlights to make sure those don't break?
- could then also use these test cases to automatically record GIFs to add to the docs. Could do this either by having talon send the full command text and save it with the test case, or build something to generate talon command from json
- For the GIF generation, we could easily automatically find all test cases that use a particular action to put into the doc for that action.  Same with transformations, etc
- Ideas for making a good GIF:
  - making text larger,
  - making command text show a good delay before action,
  - having one command per GIF so you can see the same one over and over,
  - slowing down highlight
  - put something in the gif where you can clearly see when the loop point is (thanks @timo!).  Can possibly use https://github.com/nwtgck/gif-progress
  - have 1 sec delay at start of gif (thanks @timo)
  - use longer `decorationSleepTimeout` than usual
  - somehow call out the decoration that is referenced in the command, possibly by making it bigger?  Could either do this from the start of GIF, or right after they say the command before it executes

- [ ] let's use this one to capture https://github.com/pokey/cursorless-vscode/pull/32#issuecomment-872564310 as a test case

Extra credit is:

- [ ] capture clipboard before and after
- [ ] capture visible lines before and after
- [ ] test ability to work across splits
- [ ] capture highlights

**Comment by pokey** [comment]
Note that we'll probably want to finish #69 before we record any test cases as that will change the wire format from talon

**Comment by pokey** [comment]
Use this to test:
- extracting name from exported classes and functions in Typescript
- extracting name from decorated classes and functions in Python

**Comment by pokey** [comment]
To test:

- Delimiters get removed from source of "move" and "cut"
- "that" gets set properly
- Behaviour of "wrap" wrt current selection:
  - Target selected
  - Cursor at beginning of target
  - Cursor at end of target
  - Cursor bigger than target tot left / right / both
  - Multiple cursors? (Eg one cursor at end and one at beginning, etc)

**Comment by pokey** [comment]
- space delimited sequence support when combined with punctuation, eg for "**T**his **i**s, **a** t**e**st**!**":
  - "chuck sit"
  - "move sit after each"
  - "move air after each"
  - "move each before air"
  - "bring air before bang"

**Comment by pokey** [comment]
- [ ] Make sure leading delimiter with `"chuck type"` gets deleted

**Comment by pokey** [comment]
- [ ] Test #12 and various overlapping ranges

**Comment by AndreasArvidsson** [comment]
To test
* Excluding positions in ranges. `take air until bat` `take air tween bat`

**Comment by pokey** [comment]
More to add:

- [ ] "move sit to before file"
- [ ] "chuck last char air"

**Comment by pokey** [comment]
- [ ] Make sure basic things work in unsupported languages

**Comment by pokey** [comment]
- [ ] Multi-target inference rules, eg "swap funk air with bat", "swap air with funk bat", etc

**Comment by pokey** [comment]
- [ ] select a token, then wrap it and make sure selection in right place

**Comment by pokey** [comment]
- [ ] "take token" / "take first word" when cursor is at beginning, middle and end of token
