### ISSUE TITLE
Bug with "chuck every arg"

### ISSUE THREAD

**Issue by pokey** [pokey/cursorless-vscode#63]
With the following piece of code:

```typescript
const cursorlessRecordTestCaseDisposable = vscode.commands.registerCommand(
    "cursorless.command",
    (
      actionName: ActionType,
      partialTargets: PartialTarget[],
      ...extraArgs: any[]
    ) => {}
  );
```

Calling "take every arg" on anything in the argument list results in the error message "Overlapping ranges are not allowed!"

**Comment by AndreasArvidsson** [comment]
Problem seems to be solved after the latest changes regarding delimiters
