### ISSUE TITLE
Infer type of first swap argument

### ISSUE THREAD

**Issue by pokey** [pokey/cursorless-vscode#8]
To be consistent with the way we infer the type of a start of a range based on the type of the end of the range, we could infer the type of the first swap argument from the type of the second argument. For example, "swap with funk gust", can infer that the first argument is the function containing the cursor.

**Comment by AndreasArvidsson** [comment]
Do we really want to do inference in that direction?
If you just want that functionality why don't just say: `swap funk with gust`?

I think I probably would assume that your example swaps with current selection.
