### ISSUE TITLE
Support Javascript template literals for string scope

### ISSUE THREAD

**Issue by brxck** [pokey/cursorless-vscode#86]
These nodes have the type `template_string`.

**Comment by pokey** [comment]
Ooh that's cool you mean like `foo ${hello}` to select the `${hello}`?

(Btw not sure how to get GitHub to let me put those back ticks in a code block 🤔)

**Comment by brxck** [comment]
No actually, things like "take string blue air" don't work on template literals at the moment.

Having a scope for the interpolations is a cool idea though!

**Comment by pokey** [comment]
Ah right gotcha
