### ISSUE TITLE
Fix decoration appearing after GitLens Current Line Blame

### ISSUE THREAD

**Issue by pokey** [pokey/cursorless-vscode#92]
This happens if another plugin tries to put something at the end of the line, eg GitLens's [Current Line Blame](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens#current-line-blame-).  Notice how the final gray dot is all the way off to the right:

![image](https://user-images.githubusercontent.com/755842/125114255-a2e34980-e0e1-11eb-80f6-9be1d376a1f3.png)

This could probably be fixed by using the svg `before` instead of `after`

**Comment by AndreasArvidsson** [comment]
Don't know if this of our making
![breakpoint error](https://user-images.githubusercontent.com/3511326/126536315-79d0cfbf-1810-44d4-be57-1d22c86b2cc6.png)
