### ISSUE TITLE
Add "remove cursor" action

### ISSUE THREAD

**Issue by pokey** [pokey/cursorless-vscode#95]
When using multiple cursors this would allow the user to remove a cursor that is contained in the given target

Could call it "give" (opposite of "take")

**Comment by knausj85** [comment]
I'll start looking at this one tomorrow, if no-one's workin' on it.

**Comment by AndreasArvidsson** [comment]
Go ahead. I have assigned the issue to you.
@knausj85 @pokey @brxck 
Now that we are four developers we probably should assign the issues to our self when we are working on them.
